export const header = document.createElement('header')
export const dropDown = document.createElement('ul')
export const languages = ['English', 'Russian']
export const nav = document.createElement('nav')
export const navLinks = [ 'Women', 'Man', 'Children', 'Accessories', 'Blog', 'Contact' ]
export const ul = document.createElement('ul')
export let li = document.createElement('li')
export const img  = document.createElement('img')
export const span = document.createElement('span')
export const div = document.createElement('div')
export const cartPrice = ['$0.0', 'items']